---
user_rights:
  - user: DOMAIN\monitoring
    rights:
    - SeBatchLogonRight
    - SeDenyInteractiveLogonRight
    - SeDenyRemoteInteractiveLogonRight
  - user: DOMAIN\backupservice
    rights:
    - SeBatchLogonRight
    - SeServiceLogonRight
    - SeDenyInteractiveLogonRight
    - SeDenyRemoteInteractiveLogonRight
